// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdRcNYSCv4X6cShhVjid_yH2uu5t6jVr4',
    appId: '1:798281816902:web:6805df06988ddc270c2347',
    messagingSenderId: '798281816902',
    projectId: 'shoping-fe8ac',
    authDomain: 'shoping-fe8ac.firebaseapp.com',
    storageBucket: 'shoping-fe8ac.firebasestorage.app',
    measurementId: 'G-82M7DPFQLX',
    databaseURL: "https://shoping-fe8ac-default-rtdb.firebaseio.com/"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbKO3MXoYlRXy5E3ptxCkgyeX11HhiYhI',
    appId: '1:798281816902:android:0a34e8f147edc6ac0c2347',
    messagingSenderId: '798281816902',
    projectId: 'shoping-fe8ac',
    storageBucket: 'shoping-fe8ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfRQkj7Qp5nUG4FOQUfujhphX5fh1RqLE',
    appId: '1:798281816902:ios:0458fedf2fa87ba30c2347',
    messagingSenderId: '798281816902',
    projectId: 'shoping-fe8ac',
    storageBucket: 'shoping-fe8ac.firebasestorage.app',
    iosBundleId: 'com.example.ecomerceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfRQkj7Qp5nUG4FOQUfujhphX5fh1RqLE',
    appId: '1:798281816902:ios:0458fedf2fa87ba30c2347',
    messagingSenderId: '798281816902',
    projectId: 'shoping-fe8ac',
    storageBucket: 'shoping-fe8ac.firebasestorage.app',
    iosBundleId: 'com.example.ecomerceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdRcNYSCv4X6cShhVjid_yH2uu5t6jVr4',
    appId: '1:798281816902:web:d44eda13a51ca47a0c2347',
    messagingSenderId: '798281816902',
    projectId: 'shoping-fe8ac',
    authDomain: 'shoping-fe8ac.firebaseapp.com',
    storageBucket: 'shoping-fe8ac.firebasestorage.app',
    measurementId: 'G-B3FTHTC41S',
  );
}
